### ISSUE TITLE
Building on Ubuntu fails

### ISSUE THREAD

**Issue by trenki2** [mono/xamarin-gtk-theme#33]
I tried to build on a freshly installed Ubuntu MATE 17.04 in a virtual machine.

I installed the following dependencies so that ./autogen.sh could run:

sudo apt install autoconf
sudo apt install automake
sudo apt install libtool-bin
sudo apt install intltool

I then ran ./configure and got the following error:

./configure: line 12865: AM_GLIB_GNU_GETTEXT: command not found
./configure: line 12890: syntax error near unexpected token `GTK,'
./configure: line 12890: `PKG_CHECK_MODULES(GTK, gtk+-2.0 >= 2.18.0,,'

gettext is installed. gtk should also be on the system. ./configure is complaining about a syntax error.

What can I do? What is the complete list of instructions to be able to build on a freshly installed system?

**Comment by Therzok** [comment]
Do you have `pkg-config` installed?

**Comment by trenki2** [comment]
Ok, thanks. These two additional commands were necessary:

sudo apt install pkg-config
sudo apt install libgtk2.0-dev

Then it worked.
